import type { CanvasPreset } from "../stores/preset.store";
import type { CanvasBackground } from "../stores/canvas.store";

/**
 * 7 built-in presets that mirror the Rust definitions in src-tauri/src/presets.rs.
 * Keep these in sync -- any change here must be reflected in the Rust module and vice-versa.
 *
 * The `id` field is omitted because IDs are generated at runtime when seeding
 * the preset store on first launch.
 */
export const DEFAULT_PRESETS: Omit<CanvasPreset, "id">[] = [
  {
    name: "clean-dark",
    canvasWidth: 1920,
    canvasHeight: 1080,
    padding: 80,
    background: {
      type: "solid",
      color: "#1a1a2e",
      gradientColors: ["#000000", "#000000"],
      gradientAngle: 0,
      imageSrc: null,
      blur: 0,
      grain: 0,
    } satisfies CanvasBackground,
    cornerRadius: 12,
    shadowEnabled: true,
    shadowBlur: 30,
    shadowOffsetY: 10,
    insetBorderEnabled: true,
    insetBorderWidth: 1,
  },
  {
    name: "clean-light",
    canvasWidth: 1920,
    canvasHeight: 1080,
    padding: 80,
    background: {
      type: "solid",
      color: "#f5f5f7",
      gradientColors: ["#000000", "#000000"],
      gradientAngle: 0,
      imageSrc: null,
      blur: 0,
      grain: 0,
    } satisfies CanvasBackground,
    cornerRadius: 12,
    shadowEnabled: true,
    shadowBlur: 30,
    shadowOffsetY: 10,
    insetBorderEnabled: true,
    insetBorderWidth: 1,
  },
  {
    name: "vibrant-purple",
    canvasWidth: 1920,
    canvasHeight: 1080,
    padding: 60,
    background: {
      type: "linear-gradient",
      color: "#000000",
      gradientColors: ["#667eea", "#764ba2"],
      gradientAngle: 135,
      imageSrc: null,
      blur: 0,
      grain: 0,
    } satisfies CanvasBackground,
    cornerRadius: 16,
    shadowEnabled: true,
    shadowBlur: 40,
    shadowOffsetY: 12,
    insetBorderEnabled: false,
    insetBorderWidth: 0,
  },
  {
    name: "vibrant-sunset",
    canvasWidth: 1920,
    canvasHeight: 1080,
    padding: 60,
    background: {
      type: "linear-gradient",
      color: "#000000",
      gradientColors: ["#f093fb", "#f5576c"],
      gradientAngle: 135,
      imageSrc: null,
      blur: 0,
      grain: 0,
    } satisfies CanvasBackground,
    cornerRadius: 16,
    shadowEnabled: true,
    shadowBlur: 40,
    shadowOffsetY: 12,
    insetBorderEnabled: false,
    insetBorderWidth: 0,
  },
  {
    name: "subtle-gray",
    canvasWidth: 1920,
    canvasHeight: 1080,
    padding: 60,
    background: {
      type: "solid",
      color: "#e5e5e5",
      gradientColors: ["#000000", "#000000"],
      gradientAngle: 0,
      imageSrc: null,
      blur: 0,
      grain: 0,
    } satisfies CanvasBackground,
    cornerRadius: 8,
    shadowEnabled: true,
    shadowBlur: 20,
    shadowOffsetY: 8,
    insetBorderEnabled: true,
    insetBorderWidth: 1,
  },
  {
    name: "ocean",
    canvasWidth: 1920,
    canvasHeight: 1080,
    padding: 60,
    background: {
      type: "linear-gradient",
      color: "#000000",
      gradientColors: ["#2193b0", "#6dd5ed"],
      gradientAngle: 180,
      imageSrc: null,
      blur: 0,
      grain: 0,
    } satisfies CanvasBackground,
    cornerRadius: 12,
    shadowEnabled: true,
    shadowBlur: 30,
    shadowOffsetY: 10,
    insetBorderEnabled: false,
    insetBorderWidth: 0,
  },
  {
    name: "none",
    canvasWidth: 1920,
    canvasHeight: 1080,
    padding: 0,
    background: {
      type: "solid",
      color: "#ffffff",
      gradientColors: ["#000000", "#000000"],
      gradientAngle: 0,
      imageSrc: null,
      blur: 0,
      grain: 0,
    } satisfies CanvasBackground,
    cornerRadius: 0,
    shadowEnabled: false,
    shadowBlur: 0,
    shadowOffsetY: 0,
    insetBorderEnabled: false,
    insetBorderWidth: 0,
  },
];
